version: 2
branches:
  only:
    - master
jobs:
  build:
    working_directory: /tmp/app
    docker:
      - image: andreilupu/headless-chrome-shots:jpeg
    steps:
      - checkout

      - run:
          name: Call the shots
          command: |
            set -ex
            cd /tmp/app
            mkdir json
            cd json
            mkdir demo
            mkdir test
            node /tmp/chrome-shots/shot.js --configPath=/tmp/app/.circleci/config.json

      - store_artifacts:
          path: /tmp/app/json/
          destination: screenshots/lupu

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - visual-tests